Dataset: datasets\data_132v_100x80
Config: cfg_1
Tempo de execução: 0.51 segundos

=== Saída ===
pygame 2.6.1 (SDL 2.28.4, Python 3.13.0)
Hello from the pygame community. https://www.pygame.org/contribute.html

=== Erros ===
Traceback (most recent call last):
  File "C:\Users\MATHEUS.VPS\Repos\Personal\VictimSim2\mas\main.py", line 40, in <module>
    main(data_folder_name, config_ag_folder_name)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MATHEUS.VPS\Repos\Personal\VictimSim2\mas\main.py", line 20, in main
    explorers, master_rescuer = create_explorers(env, config_ag_folder)
                                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MATHEUS.VPS\Repos\Personal\VictimSim2\mas\explorers.py", line 14, in create_explorers
    master = Rescuer(env, master_config, 4)  # 4 exploradores
  File "C:\Users\MATHEUS.VPS\Repos\Personal\VictimSim2\mas\rescuer.py", line 35, in __init__
    super().__init__(env, config_file)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\MATHEUS.VPS\Repos\Personal\VictimSim2\vs\abstract_agent.py", line 49, in __init__
    with open(config_file, "r") as file:
         ~~~~^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\MATHEUS.VPS\\Repos\\Personal\\VictimSim2\\cfg_1\\rescuer_config.txt'
